namespace: dante

commonLabels: 
  author: dante
  business: ccb-competition

commonAnnotations: 
  dockerVersion: 19.03.1
  dockerHub: https://hub.docker.com
  k8sVersion: v1.14.3
  
resources:
- ccb-springcloud-configmap
- api1-deployment.yaml
- api1-service.yaml
- api2-deployment.yaml
- api2-service.yaml
- portal-deployment.yaml
- portal-service.yaml
- gateway-deployment.yaml
- gateway-service.yaml


