node {
   stage('获取源码') {
       checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'dante-github', url: 'https://github.com/dante7qx/container-share.git']]])
   }
   
   stage('单元测试') {
       sh "mvn test"
   }
   
   stage('Sonar静态代码检查') {
       sh "echo Sonar 静态代码检查"
   }
   
   stage('编译打包') {
      sh "mvn clean package -Dmaven.test.skip=true"
   }
   
   stage('构建镜像') {
   		parallel {
   			stage('ccb-api1') {
                steps {
   				    sh "docker build -t ccb-api1:v1 --build-arg pkgName=ccb-api1 --build-arg pkgVersion=1.0 ."
                }
   			}
   			stage('ccb-api2') {
                steps {
   				    sh "docker build -t ccb-api2:v1 --build-arg pkgName=ccb-api2 --build-arg pkgVersion=1.0 ."
                }
   			}
   			stage('ccb-portal') {
                steps {
   				    sh "docker build -t ccb-portal:v1 --build-arg pkgName=ccb-portal --build-arg pkgVersion=1.0 ."
                }
   			}
   			stage('ccb-gateway') {
                steps {
   				    sh "docker build -t ccb-gateway:v1 --build-arg pkgName=ccb-gateway --build-arg pkgVersion=1.0 ."
                }
   			}
   		}
   }
   
   stage('推送镜像仓库') {
       sh """
       echo "docker tag <镜像> <镜像仓库镜像>"
       echo "docker login <镜像仓库地址> -u <用户名> -p <密码>"
       echo "docker push <镜像仓库镜像>"
       """
   }
   
   stage('应用部署') {
   		dir('deploy') {
   			sh "kubectl apply -k springcloud/"
   		}
   }
   
   stage('接口测试') {
   	   sh "echo 接口测试"
   }
   
   stage('界面测试') {
   	   sh "echo 界面测试"
   }
   
   stage('清理工作空间') {
       cleanWs()
   }
}