node {
   stage('获取源码') {
       checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'dante-github', url: 'https://github.com/dante7qx/container-share.git']]])
   }
   
   stage('单元测试') {
       sh "mvn test"
   }
   
   stage('Sonar静态代码检查') {
       sh "echo Sonar 静态代码检查"
   }
   
   stage('编译打包') {
      sh "mvn clean package -Dmaven.test.skip=true"
   }
   
   stage('构建镜像') {
        sh """
        cd deploy/
        cp ../ccb-api1/target/ccb-api1-1.0.jar ./
        docker build -t ccb-api1:v1 --build-arg pkgName=ccb-api1-1.0 .
        rm -rf ccb-api1-1.0.jar
        
        ## cp ../ccb-api2/target/ccb-api2-1.0.jar ./
        ## docker build -t ccb-api2:v1 --build-arg pkgName=ccb-api2-1.0 .
        ## rm -rf ccb-api2-1.0.jar
        
        cp ../ccb-portal/target/ccb-portal-1.0.jar ./
        docker build -t ccb-portal:v1 --build-arg pkgName=ccb-portal-1.0 .
        rm -rf ccb-portal-1.0.jar
        
        cp ../ccb-gateway/target/ccb-gateway-1.0.jar ./
        docker build -t ccb-gateway:v1 --build-arg pkgName=ccb-gateway-1.0 .
        rm -rf ccb-gateway-1.0.jar
        """
   }
   
   stage('推送镜像仓库') {
       sh """
       echo "docker tag <镜像> <镜像仓库镜像>"
       echo "docker login <镜像仓库地址> -u <用户名> -p <密码>"
       echo "docker push <镜像仓库镜像>"
       """
   }
   
   stage('应用部署') {
   		dir('deploy') {
   			sh "kubectl apply -k springcloud/"
   		}
   }
   
   stage('接口测试') {
   	   sh "echo 接口测试"
   }
   
   stage('界面测试') {
   	   sh "echo 界面测试"
   }
   
   stage('清理工作空间') {
       cleanWs()
   }
}